### PR TITLE
Writing a README file for Paladin

### PR DESCRIPTION
**Pull request by osomat123**
I created a Readme for Paladin which will help out in installing and setting up paladin for coding

### CODE REVIEW

**Comment by humdingerb** [comment]
This is supposed to be a ReadMe for Paladin. It can be assumed that the user has found and installed it. The whole HaikuDepot procedure isn't needed.
Furthermore, the ReadMe.md is supposed to give a quick overview at its github site, showing what Paladin and its main features are. There should be much more text and fewer screenshots.

I think a good approach would be to study the documentation that's included with Paladin and summarize the most essential parts of it together with a couple of screenshots (which could even be lifted from the documentation).

**Comment by osomat123** [comment]
Humdinger, I've put the installation procedure because every software has a readme file that guides through how to install the software. As you've said, I'll put in the features of paladin in this file.

**Comment by humdingerb** [comment]
The app is installed like any other software in Haiku, nothing special that has to be pointed out.
It's supposed to be a readme file used on this github page. It's supposed to give information about the app, its features, maybe its dependencies. It's not about how to use the app. That's what the documentation is for.

**Comment by osomat123** [comment]
ok sir, i'll remove the installation procedure in the final draft

**Comment by osomat123** [comment]
sir, i've made the required changes... if you could take a look at it

**Comment by osomat123** [comment]
The Readme file gives an overview of the features of Paladin, how start making a project etc.
Changes Incorporated to make the new Readme file are:
1. Addition of the 'features' section that tell you about the features of haiku
2.Highlighting of important steps, options and command lines
3.Addition of a section telling about helpful features of Paladin
4.Deletion of how to install and uninstall Paladin section
5.Reduction of unnecessary pictures
6.Poorly cropped pictures have been replaced with new ones

**Comment by humdingerb** [comment]
OK, looking good. Do this and we're finished:

1. use this screenshot for the " (Code excerpt from HexVexed) ":
hexvexed

2. Instead of "Push Alt+R to compile and run your program" write "Press Alt+R...".

3. Remove the screenshot for "Backing up projects" and "Helper tools".
Under "Helper tools" write instead of "They can be accessed from the Tools menu." 
" An ASCII table, Regular expression tester, Symbol finder and a tool to easily choose a license for your project can be accessed from the Tools menu.

**Pull request merged**
