### PR TITLE
Fix paths to header files in generated Makefiles

### LINKED ISSUE #16: Use current Makefile template
Use latest Makefile template (## Haiku Generic Makefile v2.6 ##) found in /boot/system/develop/etc/

### LINKED ISSUE #18: Incorrect paths to header files in generated makefile
When Paladin is used to generate a project makefile, the paths to system headers is incorrect
Eg. /boot/develop/headers/posix should be /boot/system/develop/headers/posix

### PR DESCRIPTION
**Pull request by BachToTheFuture**
This PR should:
* Fix #18 
* ~~I will fix #16 once I finish with #18 .~~ Fix #16

I think I'm done (for now). Feel free to make any suggestions 😃 

PS: think my commit messages randomly referenced issues 1-9 so I'm really sorry about that 🙁

### CODE REVIEW

**Comment by jscipione** [comment]
The #ifdef __HAIKU__ and other preprocessor directives should be unindented and the code inside should be indented appropriately in content (1 fewer indent level in this case).  Applies to Haiku specific (1) Haiku specific (2) commits.

**Comment by BachToTheFuture** [comment]
This line:
https://github.com/HaikuArchives/Paladin/pull/20/commits/b85917279ed6716b28ff719e895583485ff16506#diff-9eb7d70a338cbb0570710e328613413cR1351
>char temp[100];

I know there was some kind of a constant that could replace that 100, but I can't remember :(
Suggestions?

**Comment by fbrosson** [comment]
```diff
-	char temp[100];
+	char temp[PATH_MAX];
```
(it looks like the constant you are looking for is PATH_MAX.)

BTW, I saw in https://github.com/HaikuArchives/Paladin/commit/b85917279ed6716b28ff719e895583485ff16506#diff-9eb7d70a338cbb0570710e328613413cR1355 that you are taking the result of `find_directory(B_SYSTEM_DEVELOP_DIRECTORY,...)` and appending `/headers/<something>` to it. Well, it would be slightly better to take the result of `find_directory(B_SYSTEM_HEADERS_DIRECTORY,...)` and append only `/<something>` to it.

There is, indeed, a dedicated constant for the headers subdirectory:
```
~> finddir  B_SYSTEM_DEVELOP_DIRECTORY
/boot/system/develop
~> finddir  B_SYSTEM_HEADERS_DIRECTORY
/boot/system/develop/headers
```
BTW, to obtain the list of constants find_directory accepts, you can use `finddir -l`.
(What I generally do is pipe it through a `grep SYSTEM` or `grep DEVELOP` or `grep HEADERS` or `grep LIB`, because there are so many constants available ;)

**Comment by BachToTheFuture** [comment]
@fbrosson Thanks! 😄

**Comment by BachToTheFuture** [comment]
At @scottmc's request... here's the generated Makefile for HaikuArchives/WakeUp.
Paladin's Makefile generator isn't perfect (it's missing rdef files), but luckily the generated Makefile still compiles and works fine (on gcc2) 😃 
```
## Haiku Generic Makefile v2.6 ##

## Fill in this file to specify the project being created, and the referenced
## Makefile-Engine will do all of the hard work for you. This handles any
## architecture of Haiku.

# The name of the binary.
NAME = WakeUp

# The type of binary, must be one of:
#	APP:	Application
#	SHARED:	Shared library or add-on
#	STATIC:	Static library archive
#	DRIVER: Kernel driver
TYPE = APP

# 	If you plan to use localization, specify the application's MIME signature.
APP_MIME_SIG = 

#	The following lines tell Pe and Eddie where the SRCS, RDEFS, and RSRCS are
#	so that Pe and Eddie can fill them in for you.
#%{
# @src->@ 

#	Specify the source files to use. Full paths or paths relative to the 
#	Makefile can be included. All files, regardless of directory, will have
#	their object files created in the common object directory. Note that this
#	means this Makefile will not work correctly if two source files with the
#	same name (source.c or source.cpp) are included from different directories.
#	Also note that spaces in folder names do not work well with this Makefile.
SRCS =  main.cpp buzzwindow.cpp

#	Specify the resource definition files to use. Full or relative paths can be
#	used.
RDEFS = 

#	Specify the resource files to use. Full or relative paths can be used.
#	Both RDEFS and RSRCS can be utilized in the same Makefile.
RSRCS = 

# End Pe/Eddie support.
# @<-src@ 
#%}

#	Specify libraries to link against.
#	There are two acceptable forms of library specifications:
#	-	if your library follows the naming pattern of libXXX.so or libXXX.a,
#		you can simply specify XXX for the library. (e.g. the entry for
#		"libtracker.so" would be "tracker")
#
#	-	for GCC-independent linking of standard C++ libraries, you can use
#		$(STDCPPLIBS) instead of the raw "stdc++[.r4] [supc++]" library names.
#
#	- 	if your library does not follow the standard library naming scheme,
#		you need to specify the path to the library and it's name.
#		(e.g. for mylib.a, specify "mylib.a" or "path/mylib.a")
LIBS = /boot/system/lib/libbe.so /boot/system/lib/libgame.so

#	Specify additional paths to directories following the standard libXXX.so
#	or libXXX.a naming scheme. You can specify full paths or paths relative
#	to the Makefile. The paths included are not parsed recursively, so
#	include all of the paths where libraries must be found. Directories where
#	source files were specified are	automatically included.
LIBPATHS = 

#	Additional paths to look for system headers. These use the form
#	"#include <header>". Directories that contain the files in SRCS are
#	NOT auto-included here.
SYSTEM_INCLUDE_PATHS =  /boot/system/develop/headers/be /boot/system/develop/headers/cpp /boot/system/develop/headers/posix

#	Additional paths paths to look for local headers. These use the form
#	#include "header". Directories that contain the files in SRCS are
#	automatically included.
LOCAL_INCLUDE_PATHS =  .

#	Specify the level of optimization that you want. Specify either NONE (O0),
#	SOME (O1), FULL (O2), or leave blank (for the default optimization level).
OPTIMIZE := NONE

# 	Specify the codes for languages you are going to support in this
# 	application. The default "en" one must be provided too. "make catkeys"
# 	will recreate only the "locales/en.catkeys" file. Use it as a template
# 	for creating catkeys for other languages. All localization files must be
# 	placed in the "locales" subdirectory.
LOCALES = 

#	Specify all the preprocessor symbols to be defined. The symbols will not
#	have their values set automatically; you must supply the value (if any) to
#	use. For example, setting DEFINES to "DEBUG=1" will cause the compiler
#	option "-DDEBUG=1" to be used. Setting DEFINES to "DEBUG" would pass
#	"-DDEBUG" on the compiler's command line.
DEFINES = 

#	Specify the warning level. Either NONE (suppress all warnings),
#	ALL (enable all warnings), or leave blank (enable default warnings).
WARNINGS = 

#	With image symbols, stack crawls in the debugger are meaningful.
#	If set to "TRUE", symbols will be created.
SYMBOLS := 

#	Includes debug information, which allows the binary to be debugged easily.
#	If set to "TRUE", debug info will be created.
DEBUGGER := 

#	Specify any additional compiler flags to be used.
COMPILER_FLAGS = 

#	Specify any additional linker flags to be used.
LINKER_FLAGS = 

#	(Only used when "TYPE" is "DRIVER"). Specify the desired driver install
#	location in the /dev hierarchy. Example:
#		DRIVER_PATH = video/usb
#	will instruct the "driverinstall" rule to place a symlink to your driver's
#	binary in ~/add-ons/kernel/drivers/dev/video/usb, so that your driver will
#	appear at /dev/video/usb when loaded. The default is "misc".
DRIVER_PATH = 

## Include the Makefile-Engine
DEVEL_DIRECTORY := \
	$(shell findpaths -r "makefile_engine" B_FIND_PATH_DEVELOP_DIRECTORY)
include $(DEVEL_DIRECTORY)/etc/makefile-engine
```

**Comment by scottmc** [comment]
Should we merge this one first or wait until work on the other issue is added?

**Comment by BachToTheFuture** [comment]
@scottmc This builds fine on gcc2, but I don't know about x86_64, so I think I'll just make changes to the current branch/PR.

**Comment by fbrosson** [comment]
Before I forget about this, regarding the `PATH_MAX`, when I found it I had something else in mind: `B_PATH_NAME_LENGTH`.

But I don't know if there is any difference with PATH_MAX. 
(All I know is that PATH_MAX is currently set to 1024.)

**Comment by BachToTheFuture** [comment]
@fbrosson I looked at the BeBook and it says nothing about its value, but just says that path names can't be longer than `B_PATH_NAME_LENGTH`.
Honestly I don't know if I should switch, but I would stick with `PATH_MAX` until I find out what `B_PATH_NAME_LENGTH` is set to.

**Pull request merged**
