### PR TITLE
Add "generate Makefile" command line

### LINKED ISSUE #21: Add command-line option to export as a Makefile
Add a command-line option to allow opening a Paladin .pld or BeIDE .proj file and export a Makefile

### PR DESCRIPTION
**Pull request by BachToTheFuture**
Now you can generate a Makefile for a project using the `-m` option 😃 
This should fix #21.
Paladin builds and runs fine on gcc2. I don't know about x64.

### CODE REVIEW

**Comment by scottmc** [comment]
The text for the read only check seems to assume the whole disk is read only?  What if its just the file or directory that is read only?

**Comment by Vidrep** [comment]
Built and tested on 64 bit within the past hour.

**Comment by BachToTheFuture** [comment]
Thanks, @Vidrep!

**Comment by BachToTheFuture** [comment]
@scottmc:
https://github.com/HaikuArchives/Paladin/blob/7371fd5581bcce1af086aa2d7774460298360ae7/Paladin/Project.cpp#L109
and
```bool
Project::IsReadOnly(void) const
{
	return fReadOnly;
}
```
The `IsReadOnly` function only checks if the whole disk is read-only,
not individual files or directories 🙁 
If we want to check if individual files or directories are read-onlys, then we probably have to make some new functions.

**Pull request merged**
